services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu

  database:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER-ollama}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-ollama}
      POSTGRES_DB: ${POSTGRES_DB-ollama}

    volumes:
      - database_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ollama}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-api:
    build: .
    container_name: spring-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB-ollama}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      OLLAMA_HOST: ollama
      OLLAMA_PORT: 11434
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      database:
        condition: service_healthy
      ollama:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  ollama_data:
  database_data: