spring:
  application:
    name: ragapi

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL}
      embedding:
        model: ${OLLAMA_EMBEDDING_MODEL}
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
  ai:
    top-k: 5

