ALTER TABLE documents DROP CONSTRAINT IF EXISTS documents_status_check;
ALTER TABLE documents ADD CONSTRAINT documents_status_check
    CHECK (status IN ('PENDING', 'PROCESSING_CHUNKS', 'PROCESSING_EMBEDDING', 'COMPLETED', 'FAILED_CHUNKING', 'FAILED_EMBEDDING', 'ARCHIVED'));
ALTER TABLE documents ALTER COLUMN status SET DEFAULT 'PENDING';